### ISSUE TITLE
Please provide some examples.

### ISSUE THREAD

**Issue by xuzhang5788** [jingyuanz/keras-self-attention-layer#1]
Thank you for upload your implementation. 
Can it be used for the image classification problems? If yes, could you please give us some examples. Many thanks.

**Comment by jingyuanz** [comment]
Hi there, not sure how it's gonna work for image classification, coz it originates from an NLP paper https://arxiv.org/abs/1703.03130, for text classification tasks.

**Comment by mohamedScikitLearn** [comment]
Could you PLEASE show examples of Text classification? and is it compatible with TF 2.0?
